### ISSUE TITLE
Run KnoDE as a service on CentOS 7

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#1]
We need to be able to run KnoDE on system restart, under CentOS 7.

**Comment by inaimathi** [comment]
https://scottlinux.com/2014/12/08/how-to-create-a-systemd-service-in-linux-centos-7/ might be useful

**Comment by jamesaoverton** [comment]
Ok, I'll take it from there.

**Comment by jamesaoverton** [comment]
I think I got this working, following https://unix.stackexchange.com/a/236090

```
[Unit]
Description=Run ONTIE

[Service]
Type=forking
WorkingDirectory=/opt/ONTIE
ExecStart=/opt/ONTIE/run
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```
