### ISSUE TITLE
Add status page

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#13]
We should add a status page that reports on system health. If something is broken, it should be loud and obvious. The first version should:

- report various keys from `@state`
- report the number of terms; if this is 0 then indicate a problem

We should be able to use this page with an external monitoring system. The monitorign system should check for an "All system green" title (or something), otherwise notify the person in charge that there's a problem.

**Comment by inaimathi** [comment]
Preliminary thing up at https://github.com/knocean/knode/tree/basic-status-page

Although, something tells me

1. We might want to make this a JSON API endpoint if the goal is for monitoring software to ping it periodically
2. If the goal is health checks, then we should probably do something a bit more elaborate (periodically hit various GET endpoints and check for response consistency, possibly set up a heartbeat send from the server etc). My gut says that requesting only one page is a decent head-check, but will give lots of false positives on general server health.

**Comment by jamesaoverton** [comment]
Yeah, but let's start with the simplest thing.

Now the `@state` incudes an API key, so we can't just show all the data. Please just show the term count for now, and merge the code into `master`.
