### ISSUE TITLE
Implement term API

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#20]
In addition to the term status API (#19), we need a more general API for terms and the values of their predicates.

As in (#19), in principle this is a GET request, but the request could include too many terms to fit in a URL, so we'll use POST. This is a public API. The endpoint should be `/api/get-terms`. We can cap the request at 10,000 terms.

Like (#19), the user submits TSV with a column of IRIs or CURIEs. (The response should respect the choice of IRIs or CURIEs.) The main difference is that the user can choose which columns should be returned. The column names should be their predicate labels, and the sequence of columns should be put in the query string: `/api/get-terms?select=label,alternative term,definition`. The order of columns should be respected. The first column will always be IRI/CURIE.

The other difference is that the returned values are more complicated:

1. if a predicate has multiple values, then we should return all the values concatenated by pipes `|`
2. tabs and newlines and pipes have to be escaped
3. null/missing values are blank
4. we won't worry about the complexities of values types (link, plain, language, typed) for now

We can start by checking the `:terms` in `@state`, but eventually we'll have to be able to look in Blazegraph as well.

**Comment by inaimathi** [comment]
Preliminary work at https://github.com/knocean/knode/pull/24
