### ISSUE TITLE
Compare versions of upstream ontologies

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#27]
Building on #26, if an upstream ontology has changed, we need a human-readable report on the changes. Knotation was designed for human-readable ontology diffs. While some ontologies are small, we have to be able to handle large ontologies. The differences should usually be small and additive. The unit of comparison is the "term", which is a subject with an IRI (not a blank node). We want to know:

1. what terms have been removed -- ontologies can obsolete terms but should not just remove them from their namespace, so if this happens we want to know about it
2. what terms have changed, and what are the changes
3. what terms have been added, and what do they look like

The simplest thing would be to convert the two ontology versions to Knotation and do a text diff, but we might have to be more clever to get good performance on large ontologies -- the NCBI Taxonomy has ~1.5 million terms.

**Comment by inaimathi** [comment]
Preliminary version of this (that just compares for terms) is already merged. I still want to write the more elaborate one that considers term contents at some point (my last attempt at this started throwing out-of-memory errors for the large FTP ontology we were testing on).

**Comment by inaimathi** [comment]
Finished in https://github.com/knocean/knode/commit/406593ff0bce7debf47ee6a184eb4bee6efc98da
