### ISSUE TITLE
Create admin page for upstream ontologies

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#28]
Building on #27, we should have a webpage that reports all the upstream ontologies:

1. the ontology name and IRI
2. the currently loaded version IRI
3. a count of current terms
4. for authenticated users: a button to check for a new version of the ontology and report on the differences

The report on changes should have a button that will drop the old version of the ontology from the triplestore and load the new version.

**Comment by inaimathi** [comment]
Most of this is addressed in https://github.com/knocean/knode/pull/36. The remaining item is #4 (still working on the delta report page)

**Comment by inaimathi** [comment]
The remainder is addressed in https://github.com/knocean/knode/compare/upstream-delta-page?expand=1. The only bit left is reloading upstreams into the triplestore (currently, the "replace" button on the delta page replaces the ontology file on disk).

**Comment by inaimathi** [comment]
Should now be fully resolved in https://github.com/knocean/knode/pull/38
