### ISSUE TITLE
Get current Version IRI from Ontology IRI

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#35]
Given an ontology IRI such as <http://purl.obolibrary.org/obo/mro.owl> we should be able to get a version IRI such as <http://purl.obolibrary.org/obo/mro/2016-12-15/mro.owl>.

(Ideally there would be an upstream service for this,  but there isn't.)

The first time we're asked to fetch an ontology, we should store the ontology IRI, the version IRI, and the final URL that the file was fetched from. Then given an ontology IRI we can just look up the stored version IRI, or we can follow the redirects and check whether the file URL has changed.

**Comment by inaimathi** [comment]
Addressed in https://github.com/knocean/knode/pull/36
