### ISSUE TITLE
Add ClojureScript to project

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#39]
We want to start using client-side code, and I would prefer to use ClojureScript. This issue is about getting the basic structure in place for logging "Hello World" to the browser console when viewing a KnoDE web page. It will require adding a `cljs` file to the source tree, compiling it to JavaScript, making sure the browser is loading and running that compiled code, and ensuring that the compiled JavaScript is properly packaged into the JAR file that we're sharing and executing.

Bonus points for making development easy using Figwheel or whatever, but I don't want to fall down any rabbitholes.

**Comment by inaimathi** [comment]
Done in https://github.com/knocean/knode/pull/42
