### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#4]
We should enable Travis CI and add a badge to the README. (Then we should add more useful tests.)

**Comment by inaimathi** [comment]
Added the `.travis.yml` file from `howl`, but it looks like I don't have enough permissions on this repo to actually enable Travis to run.

**Comment by jamesaoverton** [comment]
I activated Travis and added a badge (77d71251b4ee886845d0bfbb3aa563bc46b51581), but the current `.travis.yml` has a `doo` task that we don't use.
