### ISSUE TITLE
Add query page

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#40]
The basics are implemented in #37. We want to add the following features:

- use Ace.js for the textarea (we will also use it for other editing forms; I have a slight preference for Ace over CodeMirror, but there might be other good options)
- history of recent queries in localstorage, so users can repeat recent queries
- list of example queries, loaded from an EDN or JSON file in the project's source tree (similar to `test/example/ontology/templates.json`)
- paging for table of results (using SPARQL's LIMIT and OFFSET)

**Comment by inaimathi** [comment]
On the last two points of this ticket. We've got a query page with Ace wired up, and a localstorage-backed query history. It still doesn't have a list of example queries, and it doesn't add paging properties to incoming queries. This work is checked into https://github.com/knocean/knode/pull/37

**Comment by inaimathi** [comment]
On the last point (add paging with SPARQL's LIMIT and OFFSET settings). Still in the same PR

**Comment by inaimathi** [comment]
All of the above is done. There's pagination built using LIMIT and OFFSET settings (unless the relevant parts are already manually specified in-query; the test cases cover what I think is the correct behavior).

Also, the front-end interface takes advantage of pagination. There's a "More" button that shows up unless the last requested page was empty. When clicked, this button gets the next page of results.
