### ISSUE TITLE
Implement tree views

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#43]
We want to be able to view ontologies along multiple hierarchies, which we'll call "trees". Each tree view will have a name, and be served from `/tree/<tree-name>`. We will have a new configuration file `/ontology/trees.edn` to configure the trees.

The basic tree data will be represented as a list of (subject, parent, label) tuples, where a subject can have multiple parents, and the parent can be null (when the subject is a root of the tree). Eventually tuples could come from a table, a SPARQL query, or an OWLAPI reasoner. For the initial version, the tuples can be literal data in the configuration file.

We need to support these representations:

- HTML: A web page showing the tree using using [Inspire Tree](http://www.inspire-tree.com).
- JSON: Inspire Tree's JSON format. Children should be sorted by label using a human-friendly sort that handles numbers properly.
- TSV: Just the tuples.
- TSV 2: The tuples, but with rows numbered, and a column indicating the path to the node as a colon-separated list of row numbers.

Because the ontologies can be large, we should support Inspire Tree's dynamic loading. So we will have to be able to request a root node and return its children, e.g. `/tree/example.json?root=EXAMPLE:0000001`. We also need a way to return just the roots of the tree (one or more).

We can build on two implementations of the tuples-to-tree code (with examples and tests):

- CLJC: https://github.com/jamesaoverton/sparql-tree/
- Python: https://gist.github.com/jamesaoverton/004a8612bd92b4e1ea8b8d7dfa88c67f

**Comment by inaimathi** [comment]
Work started in https://github.com/knocean/knode/pull/47. Mostly cleanup at this point.

**Comment by inaimathi** [comment]
More work in https://github.com/knocean/knode/pull/47. We now have

- Inspire tree display implemented and doing dynamic loading of each child level
- API implemented both for returning the full tree and returning children at a particular level
- HTML, JSON, EDN and TSV formats for both above handlers (the children handler also sorts using an implementation of `natural-compare` mostly cribbed from https://gist.github.com/wilkerlucio/db54dc83a9664124f3febf6356f04509)
- The configuration is currently read out of a file in `ontology/trees.edn`, which is assumed to contain a map of triple vectors.

What's still left as of now is

- TSV 2 (the slightly tricky part being that colon-separated row-number path

**Comment by inaimathi** [comment]
Implemented TSV 2 in the tree data handler

**Comment by inaimathi** [comment]
Merged the branch that implements all of this, but I'm leaving the issue open until I get a head-check about it.
