### ISSUE TITLE
Clean up routing table

### ISSUE THREAD

**Issue by inaimathi** [knocean/knode#49]
Right now, we're using base `compojure`, which creates a central routing table structure. This has already led to minor merge conflicts among branches. Ideally, we'd switch to a framework that allowed decentralized route declaration, or possibly rolling our own. In either case, we'd want it to expose a `ring`-compatible interface so that we could use all our existing middlewares.

**Comment by jamesaoverton** [comment]
Good idea. Can you please assess https://github.com/juxt/bidi for this?

**Comment by inaimathi** [comment]
First ground broken at https://github.com/knocean/knode/pull/51. Just starting to experiment with `bidi` (which looks like it'll do it for what we want). Still a bunch todo though:

- Make sure static handlers are supported
- Make sure URI-parameters are supported
- Make sure the `not-found` handler works as expected
- Consider factoring this out into a separate library at some point later

**Comment by jamesaoverton** [comment]
There's more cleaning up to do, but let's count this as closed by 951c4a1d536f1439170acebc936b4d7d3396656d.
