### ISSUE TITLE
Determine CURIEs and labels in `emit.cljc` not `core.cljc`

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#5]
We should refactor the TTL and RDFa functions in `emit.cljc` to take use an environment to determine CURIEs and labels from IRIs. In other words, the emit functions should only care about the IRIs determined in `core.cljc`, and `core.cljc` should only be worried about determining the right IRI.

This will allow us to parse with one set of prefixes and emit with another set of prefixes.

**Comment by inaimathi** [comment]
The only real problem with this is that we then do probably need to propagate the entire model to emitters. Not sure that's such a bad thing mind, but we need to have a way of inferring the `:curie` in cases where it's not set already.

**Comment by jamesaoverton** [comment]
Yes, the emitters need an environment. It will often be the same environment, but need not be.
