### ISSUE TITLE
Improve SPARQL input using labels

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#52]
I would like to extend SPARQL syntax to allow single-quoted labels. Given an environment (like the ones we're using for Knotation processing) and a SPARQL query string with single-quoted labels, we should translate to a normal SPARQL query that uses CURIEs or IRIs instead of labels. The resulting normal SPARQL can be submitted to the triplestore. Example: `?s 'type' ?o` would translate to `?s rdf:type ?o`.

Matching and substituting should be simple enough. We have to skip over literal strings (i.e. double-quoted strings). It would also be good to allow escaped single quotes.

Here's an earlier implementation in JavaScript, where the "Query" tab uses labels from the "Labels" tab: http://52.206.194.36

**Comment by inaimathi** [comment]
First cut up at https://github.com/knocean/knode/pull/57

**Comment by inaimathi** [comment]
Added a different regex that will ignore single quoted terms inside of double-quoted strings. If we want to get any more complex than this, I think we'll actually need to bite the bullet and use instaparse, but we're fine for now.
