### ISSUE TITLE
Experiment: Get labels for SPARQL results using a second SPARQL query

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#54]
I'm not sure this is a good idea, but it's worth trying.

Building on #53, it would be good to use labels in SPARQL results even when the environment does not contain a label. Given a paged SPARQL result set, we can collect a set of all IRIs that do not have labels in the environment, then run a SPARQL query to get the `rdfs:label` values for those IRIs. Since we're only checking labels for one page of results, the performance hit shouldn't be too bad. So the new order of preference would be:

1. label from the environment
2. label from SPARQL
3. CURIE
4. IRI

The constructed SPARQL query would look something like this:

```
SELECT DISTINCT ?subject ?label
WHERE {
  VALUES ?subject { <subject-iri-1> <subject-iri-2> ... }
  ?subject rdfs:label ?label
}
```

If a subject has more than one label, we'll sort and use the first one.

**Comment by inaimathi** [comment]
Resolved in https://github.com/knocean/knode/pull/57
