### ISSUE TITLE
Bring new version of Knode into working order

### ISSUE THREAD

**Issue by inaimathi** [knocean/knode#59]
There's a new branch of Knode at https://github.com/knocean/knode/tree/revision

Eventually, we need to get it up to feature parity with the `master` branch, but while using calls to [`knotation-editor`](https://github.com/knotation/knotation-editor) and [`knotation-cljc`](https://github.com/knotation/knotation-cljc) libraries instead of the current all-local reimplementation.

The primary bits we want to get up and running are:

- add editor call to the term page
- add template application/validation step to the term page
- allow validated terms to be added to the state in `knotation` format

**Comment by jamesaoverton** [comment]
The term pages and term status API is the first thing to do. That will bring us to feature parity with the ONTIE production site, so we can switch it out.

**Comment by inaimathi** [comment]
It looks like the first steps here then should be porting the `/api/query` handler and associated `render-result` tree (which includes term status output).

**Comment by inaimathi** [comment]
We've got the query API running; next step is adding that editor to the term page. (That is, when displaying HTML terms, an authenticated user should also see an editor with the term contents, ready to be modified).

**Comment by inaimathi** [comment]
As of https://github.com/knocean/knode/commit/847cbe7dc2d4ebafc422cd6e321104a05ff791f0 we have a basic, working (but still unauthenticated) system for adding term to the served ontology.

**Comment by inaimathi** [comment]
As of https://github.com/knocean/knode/commit/3fd8251e73f474c98fd1397bb290db7fb854bf05 we have a basic, working and authenticated system for adding terms to the served ontology.

**Comment by inaimathi** [comment]
Done and builds as of https://github.com/knocean/knode/commit/5346b3eb2514cc04bd343581d7d4061774940994
