### ISSUE TITLE
Support indented multiline strings

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#7]
We've implemented this before in HOWL, but it's always a little tricky. We can either group the lines before parsing (as in HOWL), or merge the processed blocks.

An indented multiline string consists of a statement line followed by a sequence of lines that are either (a) empty or (b) contain only spaces or (c) start with one or more spaces followed by any non-whitespace character. The indented multiline string ends with the EOF or next unindented line.

This ignores tabs, which make everything harder.

The indentation must be trimmed from the start of each line. We need to choose:

1. In HOWL we were strict about stripping two spaces. This is a bit arbitrary, and we would need a rule for handling a single space.
2. We could be strict about a single space. I worry that it would be harder for humans to distinguish indented lines.
3. We could be strict about four spaces. I have an aesthetic preference for two spaces.
4. We could be strict about tabs. Advantage: adjustable tab width. Disadvantage: mixing tabs and spaces.
5. We could follow YAML and Python, and trim based on the indentation of the first indented line.

Our overriding goal is a simple mental model for users.

**Comment by inaimathi** [comment]
The simplest model here looks like it'll be

1. Group lines before parsing
2. Trim remainder of lines based on the first indented one.

**Comment by jamesaoverton** [comment]
For multiline strings, does it make sense to require that the predicate is on a line by itself? Like so:

```
comment:
  This is a multiline string
  that has multiple lines.
```

Advantage: stronger visual distinction, maybe more consistent. Disadvantage: one more rule for users to learn.

**Comment by inaimathi** [comment]
https://github.com/knocean/knode/pull/18
