### ISSUE TITLE
Syntax error when querying all subjects

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/knode#70]
On the test server, this path `/resources/all/subjects` results in this error: `[SQLITE_ERROR] SQL error or missing database (near ")": syntax error)`.

**Comment by inaimathi** [comment]
Addressed as of https://github.com/knocean/knode/commit/413e5c0409286a11046de64701948c5a990fd41b

There's a failing test-case that's catching a rendering error in `knotation-cljc`; I'm going to fix that at the rendering layer.

**Comment by inaimathi** [comment]
Deployed to the test server. http://knode.ontodev.com/resources/all/subjects
